CREATE DATABASE RVS;

CREATE TABLE USER (
ACU_USERNAME VARCHAR(30) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL, 
LAST_NAME VARCHAR(30) NOT NULL,
EMAIL_ADDRESS VARCHAR(25),
reg_date TIMESTAMP
);

ALTER TABLE USER
ADD PRIMARY KEY (ACU_USERNAME);

CREATE TABLE TERMINAL (
ACU_USERNAME VARCHAR(30) NOT NULL,
T1 VARCHAR(30) NOT NULL, 
T2 VARCHAR(30) NOT NULL, 
T3 VARCHAR(30) NOT NULL, 
T4 VARCHAR(30) NOT NULL, 
T5 VARCHAR(30) NOT NULL,
T6 VARCHAR(30) NOT NULL, 
T7 VARCHAR(30) NOT NULL, 
T8 VARCHAR(30) NOT NULL, 
T9 VARCHAR(30) NOT NULL, 
T10 VARCHAR(30) NOT NULL, 
T11 VARCHAR(30) NOT NULL, 
T12 VARCHAR(30) NOT NULL, 
T13 VARCHAR(30) NOT NULL, 
T14 VARCHAR(30) NOT NULL,
T15 VARCHAR(30) NOT NULL, 
T16 VARCHAR(30) NOT NULL, 
T17 VARCHAR(30) NOT NULL, 
T18 VARCHAR(30) NOT NULL,
reg_date TIMESTAMP
);

ALTER TABLE TERMINAL
ADD FOREIGN KEY (ACU_USERNAME) REFERENCES USER(ACU_USERNAME);

CREATE TABLE INSTRUMENTAL (
ACU_USERNAME VARCHAR(30) NOT NULL,
I1 VARCHAR(30) NOT NULL, 
I2 VARCHAR(30) NOT NULL, 
I3 VARCHAR(30) NOT NULL, 
I4 VARCHAR(30) NOT NULL, 
I5 VARCHAR(30) NOT NULL,
I6 VARCHAR(30) NOT NULL, 
I7 VARCHAR(30) NOT NULL, 
I8 VARCHAR(30) NOT NULL, 
I9 VARCHAR(30) NOT NULL, 
I10 VARCHAR(30) NOT NULL, 
I11 VARCHAR(30) NOT NULL, 
I12 VARCHAR(30) NOT NULL, 
I13 VARCHAR(30) NOT NULL, 
I14 VARCHAR(30) NOT NULL,
I15 VARCHAR(30) NOT NULL, 
I16 VARCHAR(30) NOT NULL, 
I17 VARCHAR(30) NOT NULL, 
I18 VARCHAR(30) NOT NULL,
reg_date TIMESTAMP
);

ALTER TABLE INSTRUMENTAL
ADD FOREIGN KEY (ACU_USERNAME) REFERENCES USER(ACU_USERNAME);